name: Auto Build APK (No Local Android Studio Needed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      # ---------------------------
      # Install Android SDK
      # ---------------------------
      - name: Install Android SDK
        run: |
          set -e
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmd.zip
          unzip -q cmd.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # ---------------------------
      # Add Android platform (if missing)
      # ---------------------------
      - name: Add Android platform (if missing)
        run: |
          if [ ! -d "android" ]; then
            echo "Android folder missing — creating new one..."
            npx cap add android || true
          fi
          npx cap sync android || true

      # ---------------------------
      # Initialize Gradle if missing
      # ---------------------------
      - name: Initialize Gradle if needed
        run: |
          cd android
          if [ ! -f settings.gradle ]; then
            echo "No Gradle project detected — initializing..."
            gradle init --type basic --dsl groovy --project-name app --package com.example.app
          fi

      # ---------------------------
      # Ensure Gradle wrapper
      # ---------------------------
      - name: Ensure Gradle wrapper
        run: |
          cd android
          if [ ! -f gradlew ]; then
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x gradlew

      # ---------------------------
      # Build APK
      # ---------------------------
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon --stacktrace || gradle build

      # ---------------------------
      # Upload output APK
      # ---------------------------
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/**/*.apk
