name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      # 👇 Add Android platform if missing
      - name: Add Android platform (if missing)
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Set up JDK for Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 👇 Ensure Gradle wrapper exists
      - name: Ensure Gradle wrapper
        run: |
          cd android
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper not found — downloading..."
            wget https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle.zip
            unzip gradle.zip -d /tmp/gradle
            /tmp/gradle/gradle-8.7/bin/gradle wrapper
          fi
          chmod +x gradlew

      # 👇 Build the APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
